# Generated by Django 5.0.3 on 2024-03-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("create", "0002_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="{% static 'default.jpg' %}", upload_to="images/"
            ),
        ),
    ]
